name: 🧪 Tests

on:
  push:
    branches:
      - master

jobs:
  php-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        php: [8.2]
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create SQLite database
        run: touch database/database.sqlite

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests via PestPHP
        run: php artisan test -p
